name: invariance-test
on: 
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        #env:
        #  repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Invariance Test
        run: |
          echo "Running Invariance Test"
          python run_invariance_test.py

          # Print out the failure modes
          echo "## Failure modes" >> report.md
          git fetch --prune
          cat failure_modes.txt >> report.md