name: perturbation-test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Perturbation Test
        run: |
          echo "Running Perturbation Test"
          python run_perturbation_test.py
          
          # Print out the failure modes
          echo "## Failure modes" >> report.md
          cat failure_modes.txt >> report.md
          
          # Send it!
          cml-send-comment report.md